name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich

    - name: Build
      run: |
        make

    - name: Run Tests
      run: |
        mpirun -np 4 ./matrix_multiplication
