name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        build-essential \
        libseccomp-dev \
        pkg-config \
        squashfs-tools \
        cryptsetup \
        runc \
        wget \
        git \
        uuid-dev \
        libgpgme-dev \
        libseccomp-dev \
        pkg-config \
        uidmap \
        libssl-dev

    - name: Set up MPI
      run: |
        sudo apt-get install -y mpich

    - name: Install Go
      run: |
        wget https://dl.google.com/go/go1.20.5.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
        echo 'PATH=$PATH:/usr/local/go/bin' >> $GITHUB_ENV
        source $GITHUB_ENV
      
    - name: Install Singularity
      run: |
        export PATH=$PATH:/usr/local/go/bin
        export VERSION=4.1.3
        wget https://github.com/apptainer/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
        tar -xzf singularity-${VERSION}.tar.gz
        cd singularity
        ./mconfig
        make -C builddir
        sudo make -C builddir install
        echo 'PATH=/usr/local/singularity/bin:$PATH' >> $GITHUB_ENV
        source $GITHUB_ENV

    - name: Build
      run: |
        ./build.sh

    - name: Run Tests
      run: |
        cd build
        ./test_multiplication

    - name: Build Singularity Image
      run: |
        singularity build matrix_multiplication.sif Singularity.def

    - name: Upload Singularity image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: matrix_multiplication.sif
        path: matrix_multiplication.sif
