name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity_version: 3.8.3


    - name: Build
      run: |
        ./build.sh

    - name: Run Tests
      run: |
        cd build
        ./test_multiplication

    - name: Build Singularity Image
      run: |
        singularity build matrix_multiplication.sif Singularity.def

    - name: Upload Singularity image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: matrix_multiplication.sif
        path: matrix_multiplication.sif
