name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install MPI
      run: sudo apt-get install -y libopenmpi-dev
    
    -name: Setup Cmake
      run: sudo apt-get install -y cmake
    
    - name: Build
      run: |
        ./build.sh

    - name: Run Tests
      run: |
        cd build
        ./test_multiplication

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        build-essential \
        libseccomp-dev \
        pkg-config \
        squashfs-tools \
        cryptsetup \
        runc \
        wget \
        git \
        uuid-dev \
        libgpgme-dev \
        libseccomp-dev \
        pkg-config \
        uidmap \
        libssl-dev

    - name: Install Singularity
      run |
        wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-4.1.3.deb
        sudo dpkg -i singularity-4.1.3.deb

    - name: Build Singularity Image
      run: |
        singularity build matrix_multiplication.sif Singularity.def
