name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity_version: 3.8.3

    - name: Build Singularity Image
      run: |
        singularity build --fakeroot matrix_multiplication.sif Singularity.def
