name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich

    - name: Build
      run: |
        make

    - name: Build Singularity Container
      run: |
        sudo apt-get install -y singularity-container
        singularity build matrix_multiplication.sif Singularity.def
